
/*
 * This file was generated by the SOM Compiler.
 * FileName: WPSExtS.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.7
 *     SOM Emitter emith: 2.42
 */

#ifndef SOM_WPSAgentSam_h
#define SOM_WPSAgentSam_h


/*
 * Passthru lines: File: "C.h", "before"
 */
#define INCL_WIN
#define INCL_DOS
#include <os2.h>

#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef WPSAgentSam
#define WPSAgentSam SOMObject
#endif
#include <wpobject.h>

/*
 * Start of user-defined types:
 */
#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPFolder
    #define M_WPFolder SOMObject
#endif /* M_WPFolder */

/*
 * End of user-defined types.
 */

#define WPSAgentSam_MajorVersion 1
#define WPSAgentSam_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define WPSAgentSamNewClass c
#pragma linkage(c, system)
#define WPSAgentSamClassData d
#define WPSAgentSamCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define WPSAgentSam_classObj WPSAgentSamClassData.classObject
#define _WPSAgentSam WPSAgentSam_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK WPSAgentSamNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(WPSAgentSamNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct WPSAgentSamClassDataStructure {
	SOMClass *classObject;
} SOMDLINK WPSAgentSamClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct WPSAgentSamCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK WPSAgentSamCClassData;

/*
 * New and Renew macros for WPSAgentSam
 */
#define WPSAgentSamNew() \
   (_somNew(_WPSAgentSam ? _WPSAgentSam : WPSAgentSamNewClass(WPSAgentSam_MajorVersion, WPSAgentSam_MinorVersion)))
#define WPSAgentSamRenew(buf) \
   (_somRenew(_WPSAgentSam ? _WPSAgentSam : WPSAgentSamNewClass(WPSAgentSam_MajorVersion, WPSAgentSam_MinorVersion), buf))
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define WPSAgentSam_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define WPSAgentSam_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define WPSAgentSam_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define WPSAgentSam_wpAddSettingsPages WPObject_wpAddSettingsPages
#define WPSAgentSam_wpAddToObjUseList WPObject_wpAddToObjUseList
#define WPSAgentSam_wpAllocMem WPObject_wpAllocMem
#define WPSAgentSam_wpAppendObject WPObject_wpAppendObject
#define WPSAgentSam_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define WPSAgentSam_wpClose WPObject_wpClose
#define WPSAgentSam_wpCnrInsertObject WPObject_wpCnrInsertObject
#define WPSAgentSam_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define WPSAgentSam_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define WPSAgentSam_wpConfirmDelete WPObject_wpConfirmDelete
#define WPSAgentSam_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define WPSAgentSam_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define WPSAgentSam_wpCopyObject WPObject_wpCopyObject
#define WPSAgentSam_wpCreateAnother WPObject_wpCreateAnother
#define WPSAgentSam_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define WPSAgentSam_wpCreateShadowObject WPObject_wpCreateShadowObject
#define WPSAgentSam_wpDelete WPObject_wpDelete
#define WPSAgentSam_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define WPSAgentSam_wpDisplayHelp WPObject_wpDisplayHelp
#define WPSAgentSam_wpDisplayMenu WPObject_wpDisplayMenu
#define WPSAgentSam_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define WPSAgentSam_wpDraggedOverObject WPObject_wpDraggedOverObject
#define WPSAgentSam_wpDragOver WPObject_wpDragOver
#define WPSAgentSam_wpDrop WPObject_wpDrop
#define WPSAgentSam_wpDroppedOnObject WPObject_wpDroppedOnObject
#define WPSAgentSam_wpEndConversation WPObject_wpEndConversation
#define WPSAgentSam_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define WPSAgentSam_wpFindUseItem WPObject_wpFindUseItem
#define WPSAgentSam_wpFormatDragItem WPObject_wpFormatDragItem
#define WPSAgentSam_wpFree WPObject_wpFree
#define WPSAgentSam_wpFreeMem WPObject_wpFreeMem
#define WPSAgentSam_wpHide WPObject_wpHide
#define WPSAgentSam_wpInitData WPObject_wpInitData
#define WPSAgentSam_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define WPSAgentSam_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define WPSAgentSam_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define WPSAgentSam_wpMenuItemSelected WPObject_wpMenuItemSelected
#define WPSAgentSam_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define WPSAgentSam_wpMoveObject WPObject_wpMoveObject
#define WPSAgentSam_wpOpen WPObject_wpOpen
#define WPSAgentSam_wpPrintObject WPObject_wpPrintObject
#define WPSAgentSam_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define WPSAgentSam_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define WPSAgentSam_wpQueryConfirmations WPObject_wpQueryConfirmations
#define WPSAgentSam_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define WPSAgentSam_wpQueryDefaultView WPObject_wpQueryDefaultView
#define WPSAgentSam_wpQueryDetailsData WPObject_wpQueryDetailsData
#define WPSAgentSam_wpQueryError WPObject_wpQueryError
#define WPSAgentSam_wpSetFolder WPObject_wpSetFolder
#define WPSAgentSam_wpQueryFolder WPObject_wpQueryFolder
#define WPSAgentSam_wpQueryIcon WPObject_wpQueryIcon
#define WPSAgentSam_wpQueryIconData WPObject_wpQueryIconData
#define WPSAgentSam_wpQueryMinWindow WPObject_wpQueryMinWindow
#define WPSAgentSam_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define WPSAgentSam_wpQueryStyle WPObject_wpQueryStyle
#define WPSAgentSam_wpSetTaskRec WPObject_wpSetTaskRec
#define WPSAgentSam_wpFindTaskRec WPObject_wpFindTaskRec
#define WPSAgentSam_wpQueryTitle WPObject_wpQueryTitle
#define WPSAgentSam_wpRegisterView WPObject_wpRegisterView
#define WPSAgentSam_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define WPSAgentSam_wpRender WPObject_wpRender
#define WPSAgentSam_wpRenderComplete WPObject_wpRenderComplete
#define WPSAgentSam_wpReplaceObject WPObject_wpReplaceObject
#define WPSAgentSam_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define WPSAgentSam_wpRestore WPObject_wpRestore
#define WPSAgentSam_wpRestoreData WPObject_wpRestoreData
#define WPSAgentSam_wpRestoreLong WPObject_wpRestoreLong
#define WPSAgentSam_wpRestoreState WPObject_wpRestoreState
#define WPSAgentSam_wpRestoreString WPObject_wpRestoreString
#define WPSAgentSam_wpSaveData WPObject_wpSaveData
#define WPSAgentSam_wpSaveImmediate WPObject_wpSaveImmediate
#define WPSAgentSam_wpSaveDeferred WPObject_wpSaveDeferred
#define WPSAgentSam_wpSaveLong WPObject_wpSaveLong
#define WPSAgentSam_wpSaveState WPObject_wpSaveState
#define WPSAgentSam_wpSaveString WPObject_wpSaveString
#define WPSAgentSam_wpScanSetupString WPObject_wpScanSetupString
#define WPSAgentSam_wpSetConcurrentView WPObject_wpSetConcurrentView
#define WPSAgentSam_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define WPSAgentSam_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define WPSAgentSam_wpSetDefaultView WPObject_wpSetDefaultView
#define WPSAgentSam_wpSetError WPObject_wpSetError
#define WPSAgentSam_wpSetIconHandle WPObject_wpSetIconHandle
#define WPSAgentSam_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define WPSAgentSam_wpSetupOnce WPObject_wpSetupOnce
#define WPSAgentSam_wpSetIcon WPObject_wpSetIcon
#define WPSAgentSam_wpSetIconData WPObject_wpSetIconData
#define WPSAgentSam_wpSetMinWindow WPObject_wpSetMinWindow
#define WPSAgentSam_wpSetStyle WPObject_wpSetStyle
#define WPSAgentSam_wpModifyStyle WPObject_wpModifyStyle
#define WPSAgentSam_wpSetTitle WPObject_wpSetTitle
#define WPSAgentSam_wpSetup WPObject_wpSetup
#define WPSAgentSam_wpSwitchTo WPObject_wpSwitchTo
#define WPSAgentSam_wpUnInitData WPObject_wpUnInitData
#define WPSAgentSam_wpViewObject WPObject_wpViewObject
#define WPSAgentSam_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define WPSAgentSam_wpQueryHandle WPObject_wpQueryHandle
#define WPSAgentSam_wpUnlockObject WPObject_wpUnlockObject
#define WPSAgentSam_wpObjectReady WPObject_wpObjectReady
#define WPSAgentSam_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define WPSAgentSam_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define WPSAgentSam_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define WPSAgentSam_wpIsDeleteable WPObject_wpIsDeleteable
#define WPSAgentSam_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define WPSAgentSam_wpSetObjectID WPObject_wpSetObjectID
#define WPSAgentSam_wpQueryObjectID WPObject_wpQueryObjectID
#define WPSAgentSam_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define WPSAgentSam_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define WPSAgentSam_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define WPSAgentSam_wpFindViewItem WPObject_wpFindViewItem
#define WPSAgentSam_wpLockObject WPObject_wpLockObject
#define WPSAgentSam_wpIsLocked WPObject_wpIsLocked
#define WPSAgentSam_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define WPSAgentSam_wpWaitForClose WPObject_wpWaitForClose
#define WPSAgentSam_somDefaultInit SOMObject_somDefaultInit
#define WPSAgentSam_somDestruct SOMObject_somDestruct
#define WPSAgentSam_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define WPSAgentSam_somDefaultAssign SOMObject_somDefaultAssign
#define WPSAgentSam_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define WPSAgentSam_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define WPSAgentSam_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define WPSAgentSam_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define WPSAgentSam_somDefaultVAssign SOMObject_somDefaultVAssign
#define WPSAgentSam_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define WPSAgentSam_somInit SOMObject_somInit
#define WPSAgentSam_somFree SOMObject_somFree
#define WPSAgentSam_somUninit SOMObject_somUninit
#define WPSAgentSam_somGetClass SOMObject_somGetClass
#define WPSAgentSam_somGetClassName SOMObject_somGetClassName
#define WPSAgentSam_somGetSize SOMObject_somGetSize
#define WPSAgentSam_somIsA SOMObject_somIsA
#define WPSAgentSam_somIsInstanceOf SOMObject_somIsInstanceOf
#define WPSAgentSam_somRespondsTo SOMObject_somRespondsTo
#define WPSAgentSam_somDispatch SOMObject_somDispatch
#define WPSAgentSam_somClassDispatch SOMObject_somClassDispatch
#define WPSAgentSam_somCastObj SOMObject_somCastObj
#define WPSAgentSam_somResetObj SOMObject_somResetObj
#define WPSAgentSam_somDispatchV SOMObject_somDispatchV
#define WPSAgentSam_somDispatchL SOMObject_somDispatchL
#define WPSAgentSam_somDispatchA SOMObject_somDispatchA
#define WPSAgentSam_somDispatchD SOMObject_somDispatchD
#define WPSAgentSam_somPrintSelf SOMObject_somPrintSelf
#define WPSAgentSam_somDumpSelf SOMObject_somDumpSelf
#define WPSAgentSam_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_WPSAgentSam_h */

#ifndef SOM_FFolder_h
#define SOM_FFolder_h


/*
 * Passthru lines: File: "C.h", "before"
 */
#define INCL_WIN
#define INCL_DOS
#include <os2.h>
#include "fnmatch.h"

#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef FFolder
#define FFolder SOMObject
#endif
#include <wpfolder.h>

/*
 * Start of user-defined types:
 */

/*
 * End of user-defined types.
 */

#define FFolder_MajorVersion 1
#define FFolder_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define FFolderNewClass c
#pragma linkage(c, system)
#define FFolderClassData d
#define FFolderCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define FFolder_classObj FFolderClassData.classObject
#define _FFolder FFolder_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK FFolderNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(FFolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct FFolderClassDataStructure {
	SOMClass *classObject;
	somMToken _get_filter;
	somMToken _set_filter;
	somMToken _get_filtered;
	somMToken _set_filtered;
} SOMDLINK FFolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct FFolderCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK FFolderCClassData;

/*
 * New and Renew macros for FFolder
 */
#define FFolderNew() \
   (_somNew(_FFolder ? _FFolder : FFolderNewClass(FFolder_MajorVersion, FFolder_MinorVersion)))
#define FFolderRenew(buf) \
   (_somRenew(_FFolder ? _FFolder : FFolderNewClass(FFolder_MajorVersion, FFolder_MinorVersion), buf))

/*
 * Override method: wpInitData
 */
#define FFolder_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpViewObject
 */
#define FFolder_wpViewObject(somSelf,hwndCnr,ulView,param) \
	WPObject_wpViewObject(somSelf,hwndCnr,ulView,param)

/*
 * Override method: wpPopulate
 */
#define FFolder_wpPopulate(somSelf,ulReserved,pszPath,fFoldersOnly) \
	WPFolder_wpPopulate(somSelf,ulReserved,pszPath,fFoldersOnly)

/*
 * Override method: wpSetup
 */
#define FFolder_wpSetup(somSelf,pszSetupString) \
	WPObject_wpSetup(somSelf,pszSetupString)

/*
 * Override method: wpDeleteFromObjUseList
 */
#define FFolder_wpDeleteFromObjUseList(somSelf,pUseItem) \
	WPObject_wpDeleteFromObjUseList(somSelf,pUseItem)

/*
 * New Method: _get_filter
 */
typedef string   SOMLINK somTP_FFolder__get_filter(FFolder *somSelf, Environment *ev);
#pragma linkage(somTP_FFolder__get_filter, system)
typedef somTP_FFolder__get_filter *somTD_FFolder__get_filter;
#define somMD_FFolder__get_filter "::FFolder::_get_filter"
#define FFolder__get_filter(somSelf,ev) \
    (SOM_Resolve(somSelf, FFolder, _get_filter) \
	(somSelf,ev))
#ifndef SOMGD_get_filter
    #if (defined(_get_filter) || defined(__get_filter))
        #undef _get_filter
        #undef __get_filter
        #define SOMGD_get_filter 1
    #else
        #define __get_filter FFolder__get_filter
    #endif /* __get_filter */
#endif /* SOMGD_get_filter */

/*
 * New Method: _set_filter
 */
typedef void   SOMLINK somTP_FFolder__set_filter(FFolder *somSelf, Environment *ev,
		string filter);
#pragma linkage(somTP_FFolder__set_filter, system)
typedef somTP_FFolder__set_filter *somTD_FFolder__set_filter;
#define somMD_FFolder__set_filter "::FFolder::_set_filter"
#define FFolder__set_filter(somSelf,ev,filter) \
    (SOM_Resolve(somSelf, FFolder, _set_filter) \
	(somSelf,ev,filter))
#ifndef SOMGD_set_filter
    #if (defined(_set_filter) || defined(__set_filter))
        #undef _set_filter
        #undef __set_filter
        #define SOMGD_set_filter 1
    #else
        #define __set_filter FFolder__set_filter
    #endif /* __set_filter */
#endif /* SOMGD_set_filter */

/*
 * New Method: _get_filtered
 */
typedef boolean   SOMLINK somTP_FFolder__get_filtered(FFolder *somSelf, Environment *ev);
#pragma linkage(somTP_FFolder__get_filtered, system)
typedef somTP_FFolder__get_filtered *somTD_FFolder__get_filtered;
#define somMD_FFolder__get_filtered "::FFolder::_get_filtered"
#define FFolder__get_filtered(somSelf,ev) \
    (SOM_Resolve(somSelf, FFolder, _get_filtered) \
	(somSelf,ev))
#ifndef SOMGD_get_filtered
    #if (defined(_get_filtered) || defined(__get_filtered))
        #undef _get_filtered
        #undef __get_filtered
        #define SOMGD_get_filtered 1
    #else
        #define __get_filtered FFolder__get_filtered
    #endif /* __get_filtered */
#endif /* SOMGD_get_filtered */

/*
 * New Method: _set_filtered
 */
typedef void   SOMLINK somTP_FFolder__set_filtered(FFolder *somSelf, Environment *ev,
		boolean filtered);
#pragma linkage(somTP_FFolder__set_filtered, system)
typedef somTP_FFolder__set_filtered *somTD_FFolder__set_filtered;
#define somMD_FFolder__set_filtered "::FFolder::_set_filtered"
#define FFolder__set_filtered(somSelf,ev,filtered) \
    (SOM_Resolve(somSelf, FFolder, _set_filtered) \
	(somSelf,ev,filtered))
#ifndef SOMGD_set_filtered
    #if (defined(_set_filtered) || defined(__set_filtered))
        #undef _set_filtered
        #undef __set_filtered
        #define SOMGD_set_filtered 1
    #else
        #define __set_filtered FFolder__set_filtered
    #endif /* __set_filtered */
#endif /* SOMGD_set_filtered */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define FFolder_wpSetFldrFlags WPFolder_wpSetFldrFlags
#define FFolder_wpQueryFldrFlags WPFolder_wpQueryFldrFlags
#define FFolder_wpSetFldrFont WPFolder_wpSetFldrFont
#define FFolder_wpQueryFldrFont WPFolder_wpQueryFldrFont
#define FFolder_wpSetFldrAttr WPFolder_wpSetFldrAttr
#define FFolder_wpQueryFldrAttr WPFolder_wpQueryFldrAttr
#define FFolder_wpSetNextIconPos WPFolder_wpSetNextIconPos
#define FFolder_wpQueryNextIconPos WPFolder_wpQueryNextIconPos
#define FFolder_wpQueryContent WPFolder_wpQueryContent
#define FFolder_wpAddFolderView1Page WPFolder_wpAddFolderView1Page
#define FFolder_wpAddFolderView2Page WPFolder_wpAddFolderView2Page
#define FFolder_wpAddFolderView3Page WPFolder_wpAddFolderView3Page
#define FFolder_wpAddFolderIncludePage WPFolder_wpAddFolderIncludePage
#define FFolder_wpAddFolderSortPage WPFolder_wpAddFolderSortPage
#define FFolder_wpAddFolderBackgroundPage WPFolder_wpAddFolderBackgroundPage
#define FFolder_wpAddFolderSelfClosePage WPFolder_wpAddFolderSelfClosePage
#define FFolder_wpInitIconPosData WPFolder_wpInitIconPosData
#define FFolder_wpFreeIconPosData WPFolder_wpFreeIconPosData
#define FFolder_wpStoreIconPosData WPFolder_wpStoreIconPosData
#define FFolder_wpQueryIconPosition WPFolder_wpQueryIconPosition
#define FFolder_wpSetFldrSort WPFolder_wpSetFldrSort
#define FFolder_wpQueryFldrSort WPFolder_wpQueryFldrSort
#define FFolder_wpRestoreFldrRunObjs WPFolder_wpRestoreFldrRunObjs
#define FFolder_wpStoreFldrRunObjs WPFolder_wpStoreFldrRunObjs
#define FFolder_wpHideFldrRunObjs WPFolder_wpHideFldrRunObjs
#define FFolder_wpDeleteContents WPFolder_wpDeleteContents
#define FFolder_wpSetFldrDetailsClass WPFolder_wpSetFldrDetailsClass
#define FFolder_wpQueryFldrDetailsClass WPFolder_wpQueryFldrDetailsClass
#define FFolder_wpSearchFolder WPFolder_wpSearchFolder
#define FFolder_wpContainsFolders WPFolder_wpContainsFolders
#define FFolder_wpQueryOpenFolders WPFolder_wpQueryOpenFolders
#define FFolder_wpModifyFldrFlags WPFolder_wpModifyFldrFlags
#define FFolder_wpAddToContent WPFolder_wpAddToContent
#define FFolder_wpDeleteFromContent WPFolder_wpDeleteFromContent
#define FFolder_wpSetDetailsColumnVisibility WPFolder_wpSetDetailsColumnVisibility
#define FFolder_wpIsDetailsColumnVisible WPFolder_wpIsDetailsColumnVisible
#define FFolder_wpSetFldrSortClass WPFolder_wpSetFldrSortClass
#define FFolder_wpQueryFldrSortClass WPFolder_wpQueryFldrSortClass
#define FFolder_wpSetSortAttribAvailable WPFolder_wpSetSortAttribAvailable
#define FFolder_wpIsSortAttribAvailable WPFolder_wpIsSortAttribAvailable
#define FFolder_wpQueryIconViewPos WPFolder_wpQueryIconViewPos
#define FFolder_wpAddFirstChild WPFolder_wpAddFirstChild
#define FFolder_wpSetRealName WPFileSystem_wpSetRealName
#define FFolder_wpSetType WPFileSystem_wpSetType
#define FFolder_wpQueryType WPFileSystem_wpQueryType
#define FFolder_wpSetAttr WPFileSystem_wpSetAttr
#define FFolder_wpQueryAttr WPFileSystem_wpQueryAttr
#define FFolder_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define FFolder_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define FFolder_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define FFolder_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define FFolder_wpQueryCreation WPFileSystem_wpQueryCreation
#define FFolder_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define FFolder_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define FFolder_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define FFolder_wpQueryEASize WPFileSystem_wpQueryEASize
#define FFolder_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define FFolder_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define FFolder_wpRefresh WPFileSystem_wpRefresh
#define FFolder_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define FFolder_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define FFolder_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define FFolder_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define FFolder_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define FFolder_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define FFolder_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define FFolder_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define FFolder_wpQueryRealName WPFileSystem_wpQueryRealName
#define FFolder_wpQueryFilename WPFileSystem_wpQueryFilename
#define FFolder_wpQueryDisk WPFileSystem_wpQueryDisk
#define FFolder_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define FFolder_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define FFolder_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define FFolder_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define FFolder_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define FFolder_wpAddSettingsPages WPObject_wpAddSettingsPages
#define FFolder_wpAddToObjUseList WPObject_wpAddToObjUseList
#define FFolder_wpAllocMem WPObject_wpAllocMem
#define FFolder_wpAppendObject WPObject_wpAppendObject
#define FFolder_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define FFolder_wpClose WPObject_wpClose
#define FFolder_wpCnrInsertObject WPObject_wpCnrInsertObject
#define FFolder_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define FFolder_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define FFolder_wpConfirmDelete WPObject_wpConfirmDelete
#define FFolder_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define FFolder_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define FFolder_wpCopyObject WPObject_wpCopyObject
#define FFolder_wpCreateAnother WPObject_wpCreateAnother
#define FFolder_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define FFolder_wpCreateShadowObject WPObject_wpCreateShadowObject
#define FFolder_wpDelete WPObject_wpDelete
#define FFolder_wpDisplayHelp WPObject_wpDisplayHelp
#define FFolder_wpDisplayMenu WPObject_wpDisplayMenu
#define FFolder_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define FFolder_wpDraggedOverObject WPObject_wpDraggedOverObject
#define FFolder_wpDragOver WPObject_wpDragOver
#define FFolder_wpDrop WPObject_wpDrop
#define FFolder_wpDroppedOnObject WPObject_wpDroppedOnObject
#define FFolder_wpEndConversation WPObject_wpEndConversation
#define FFolder_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define FFolder_wpFindUseItem WPObject_wpFindUseItem
#define FFolder_wpFormatDragItem WPObject_wpFormatDragItem
#define FFolder_wpFree WPObject_wpFree
#define FFolder_wpFreeMem WPObject_wpFreeMem
#define FFolder_wpHide WPObject_wpHide
#define FFolder_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define FFolder_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define FFolder_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define FFolder_wpMenuItemSelected WPObject_wpMenuItemSelected
#define FFolder_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define FFolder_wpMoveObject WPObject_wpMoveObject
#define FFolder_wpOpen WPObject_wpOpen
#define FFolder_wpPrintObject WPObject_wpPrintObject
#define FFolder_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define FFolder_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define FFolder_wpQueryConfirmations WPObject_wpQueryConfirmations
#define FFolder_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define FFolder_wpQueryDefaultView WPObject_wpQueryDefaultView
#define FFolder_wpQueryDetailsData WPObject_wpQueryDetailsData
#define FFolder_wpQueryError WPObject_wpQueryError
#define FFolder_wpSetFolder WPObject_wpSetFolder
#define FFolder_wpQueryFolder WPObject_wpQueryFolder
#define FFolder_wpQueryIcon WPObject_wpQueryIcon
#define FFolder_wpQueryIconData WPObject_wpQueryIconData
#define FFolder_wpQueryMinWindow WPObject_wpQueryMinWindow
#define FFolder_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define FFolder_wpQueryStyle WPObject_wpQueryStyle
#define FFolder_wpSetTaskRec WPObject_wpSetTaskRec
#define FFolder_wpFindTaskRec WPObject_wpFindTaskRec
#define FFolder_wpQueryTitle WPObject_wpQueryTitle
#define FFolder_wpRegisterView WPObject_wpRegisterView
#define FFolder_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define FFolder_wpRender WPObject_wpRender
#define FFolder_wpRenderComplete WPObject_wpRenderComplete
#define FFolder_wpReplaceObject WPObject_wpReplaceObject
#define FFolder_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define FFolder_wpRestore WPObject_wpRestore
#define FFolder_wpRestoreData WPObject_wpRestoreData
#define FFolder_wpRestoreLong WPObject_wpRestoreLong
#define FFolder_wpRestoreState WPObject_wpRestoreState
#define FFolder_wpRestoreString WPObject_wpRestoreString
#define FFolder_wpSaveData WPObject_wpSaveData
#define FFolder_wpSaveImmediate WPObject_wpSaveImmediate
#define FFolder_wpSaveDeferred WPObject_wpSaveDeferred
#define FFolder_wpSaveLong WPObject_wpSaveLong
#define FFolder_wpSaveState WPObject_wpSaveState
#define FFolder_wpSaveString WPObject_wpSaveString
#define FFolder_wpScanSetupString WPObject_wpScanSetupString
#define FFolder_wpSetConcurrentView WPObject_wpSetConcurrentView
#define FFolder_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define FFolder_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define FFolder_wpSetDefaultView WPObject_wpSetDefaultView
#define FFolder_wpSetError WPObject_wpSetError
#define FFolder_wpSetIconHandle WPObject_wpSetIconHandle
#define FFolder_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define FFolder_wpSetupOnce WPObject_wpSetupOnce
#define FFolder_wpSetIcon WPObject_wpSetIcon
#define FFolder_wpSetIconData WPObject_wpSetIconData
#define FFolder_wpSetMinWindow WPObject_wpSetMinWindow
#define FFolder_wpSetStyle WPObject_wpSetStyle
#define FFolder_wpModifyStyle WPObject_wpModifyStyle
#define FFolder_wpSetTitle WPObject_wpSetTitle
#define FFolder_wpSwitchTo WPObject_wpSwitchTo
#define FFolder_wpUnInitData WPObject_wpUnInitData
#define FFolder_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define FFolder_wpQueryHandle WPObject_wpQueryHandle
#define FFolder_wpUnlockObject WPObject_wpUnlockObject
#define FFolder_wpObjectReady WPObject_wpObjectReady
#define FFolder_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define FFolder_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define FFolder_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define FFolder_wpIsDeleteable WPObject_wpIsDeleteable
#define FFolder_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define FFolder_wpSetObjectID WPObject_wpSetObjectID
#define FFolder_wpQueryObjectID WPObject_wpQueryObjectID
#define FFolder_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define FFolder_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define FFolder_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define FFolder_wpFindViewItem WPObject_wpFindViewItem
#define FFolder_wpLockObject WPObject_wpLockObject
#define FFolder_wpIsLocked WPObject_wpIsLocked
#define FFolder_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define FFolder_wpWaitForClose WPObject_wpWaitForClose
#define FFolder_somDefaultInit SOMObject_somDefaultInit
#define FFolder_somDestruct SOMObject_somDestruct
#define FFolder_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define FFolder_somDefaultAssign SOMObject_somDefaultAssign
#define FFolder_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define FFolder_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define FFolder_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define FFolder_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define FFolder_somDefaultVAssign SOMObject_somDefaultVAssign
#define FFolder_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define FFolder_somInit SOMObject_somInit
#define FFolder_somFree SOMObject_somFree
#define FFolder_somUninit SOMObject_somUninit
#define FFolder_somGetClass SOMObject_somGetClass
#define FFolder_somGetClassName SOMObject_somGetClassName
#define FFolder_somGetSize SOMObject_somGetSize
#define FFolder_somIsA SOMObject_somIsA
#define FFolder_somIsInstanceOf SOMObject_somIsInstanceOf
#define FFolder_somRespondsTo SOMObject_somRespondsTo
#define FFolder_somDispatch SOMObject_somDispatch
#define FFolder_somClassDispatch SOMObject_somClassDispatch
#define FFolder_somCastObj SOMObject_somCastObj
#define FFolder_somResetObj SOMObject_somResetObj
#define FFolder_somDispatchV SOMObject_somDispatchV
#define FFolder_somDispatchL SOMObject_somDispatchL
#define FFolder_somDispatchA SOMObject_somDispatchA
#define FFolder_somDispatchD SOMObject_somDispatchD
#define FFolder_somPrintSelf SOMObject_somPrintSelf
#define FFolder_somDumpSelf SOMObject_somDumpSelf
#define FFolder_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_FFolder_h */
